name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          port: '${{ secrets.PORT }}'
          key: "${{ secrets.SSH_KEY }}"
          script: 'echo "SSH connection successful."'

      - name: Fetch latest changes
        uses: tiyee/action-ssh@v1.0.1
        with:
          command: |
            cd /home/docker/stacks/izegem-klinkt-nuxt
            git pull

      - name: Deploy via SSH
        uses: tiyee/action-ssh@v1.0.1
        with:
          command: |
            cd /home/docker/stacks/izegem-klinkt-nuxt
      
            if docker ps -a --format '{{.Names}}' | grep izegem-klinkt-nuxt; then
              echo "Container exists, restarting..."
              docker compose down
              docker compose up -d --build
            else
              echo "Container does not exist, creating a new one..."
              docker compose up -d --build
            fi
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          port: '${{ secrets.PORT }}'
          privateKey: "${{ secrets.SSH_KEY }}"
